/**
 * codUI.js — v2.0.8
 * Lightweight, zero-dependency Web Component for code syntax highlighting.
 *
 * !! DO NOT EDIT THIS FILE DIRECTLY !!
 * This file is auto-generated by: node scripts/build.js
 * Source files live in: src/
 *
 * Usage: <cod-ui lang="js" theme="dark" line-numbers="true">...</cod-ui>
 * Docs:  https://github.com/praTeek271/codUI
 */

(function () {
'use strict';


// ─── utils.js ─────────────────────────────────────────────────


/**
 * src/lib/utils.js
 * Shared utility functions available across the entire bundle.
 * Loaded first in build order — all other modules depend on these.
 */

/**
 * Escapes HTML special characters to their entity equivalents.
 * Used before passing raw user code into the highlighter.
 * @param {string} str
 * @returns {string}
 */
function escapeHTML(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

/**
 * Trims leading and trailing blank lines from a raw code string.
 * Preserves internal indentation exactly.
 * @param {string} str
 * @returns {string}
 */
function stripNewlines(str) {
    return str.replace(/^\s*[\r\n]/, '').replace(/[\r\n]\s*$/, '');
}

/**
 * Counts the number of lines in a string.
 * @param {string} str
 * @returns {number}
 */
function countLines(str) {
    return (str.match(/\n/g) || []).length + 1;
}


// ─── regex.js ─────────────────────────────────────────────────


/**
 * src/lib/regex.js
 * Centralized regex pattern library for all language tokenizers.
 * Language files (src/lang/*.js) MUST use these patterns — never define inline regex.
 *
 * Each entry is a factory function that returns a fresh RegExp.
 * This prevents lastIndex bleed-through when the same pattern is called
 * multiple times across different tokenize() invocations.
 */

var PATTERNS = {

    // ── Comments ──────────────────────────────────────────────────────────────

    /** Hash-style single line comment: # this is a comment */
    COMMENT_HASH:    function() { return /(#[^\n]*)/g; },

    /** Double-slash single line comment: // this is a comment */
    COMMENT_SLASH:   function() { return /(\/\/[^\n]*)/g; },

    /** Block comment: /* ... *\/ */
    COMMENT_BLOCK:   function() { return /(\/\*[\s\S]*?\*\/)/g; },

    /** HTML/XML comment: <!-- ... --> (operates on HTML-escaped source) */
    COMMENT_HTML:    function() { return /(&lt;!--[\s\S]*?--&gt;)/g; },

    // ── Strings ───────────────────────────────────────────────────────────────

    /** Double-quoted string (supports escaped quotes inside) */
    STRING_DOUBLE:   function() { return /("(?:[^"\\]|\\.)*")/g; },

    /** Single-quoted string (supports escaped chars inside) */
    STRING_SINGLE:   function() { return /('(?:[^'\\]|\\.)*')/g; },

    /** Backtick template literal */
    STRING_BACKTICK: function() { return /(`(?:[^`\\]|\\.)*`)/g; },

    // ── Numbers ───────────────────────────────────────────────────────────────

    /** Integer, float, scientific notation: 42, 3.14, 1e-10 */
    NUMBER_GENERAL: function() { return /\b(\d+(\.\d+)?([eE][+-]?\d+)?)\b/g; },

    /** Negative numbers and JSON numbers */
    NUMBER_JSON:    function() { return /\b(-?\d+(\.\d+)?([eE][+-]?\d+)?)\b/g; },

    /** CSS numbers with optional units: 12px, 1.5rem, 100%, 0.3s */
    NUMBER_CSS:     function() { return /\b(\d+(\.\d+)?(px|rem|em|%|vh|vw|vmin|vmax|s|ms|deg|fr)?)\b/g; },

    // ── Functions ─────────────────────────────────────────────────────────────

    /** Any identifier immediately followed by an opening parenthesis */
    FUNCTION_CALL:  function() { return /\b([a-zA-Z_$][\w$]*)(?=\s*\()/g; },

    // ── HTML / XML ────────────────────────────────────────────────────────────

    /** Opening/closing HTML tag name (on escaped source: &lt;div) */
    HTML_TAG:       function() { return /(&lt;\/?)([\w\-:]+)/g; },

    /** HTML attribute name (word before =) */
    HTML_ATTR:      function() { return /\b([\w\-:]+)(?=\s*=)/g; },

    // ── CSS ───────────────────────────────────────────────────────────────────

    /** CSS custom property / variable: --primary-color */
    CSS_VAR:        function() { return /(--[\w-]+)/g; },

    /** CSS property name (word before colon) */
    CSS_PROP:       function() { return /([\w-]+)(?=\s*:)/g; },

    // ── JSON ──────────────────────────────────────────────────────────────────

    /** JSON object key: "key": (double-quoted string before a colon) */
    JSON_KEY:       function() { return /"([^"]+)"(?=\s*:)/g; },

    /** JSON string value (double-quoted, NOT followed by colon) */
    JSON_STRING:    function() { return /"([^"]+)"(?!\s*:)/g; },

    // ── Bash / Shell ──────────────────────────────────────────────────────────

    /** Bash variable expansion: $VAR or ${VAR} */
    BASH_VAR:       function() { return /(\$\{?[\w_]+\}?)/g; },

};

/**
 * Builds a word-boundary regex from an array of keyword strings.
 * Always returns a fresh RegExp instance.
 * @param {string[]} words
 * @returns {RegExp}
 */
function makeKeywordRegex(words) {
    return new RegExp('\\b(' + words.join('|') + ')\\b', 'g');
}


// ─── themes.js ────────────────────────────────────────────────


/**
 * src/lib/themes.js
 * Theme definitions and CSS generation for the CodUI Web Component.
 *
 * Each theme defines:
 *   - UI colors  : bg, header, text, border, lineNum, borderStyle
 *   - Syntax colors: keyword, control, function, string, comment, number, tag, attr
 *
 * Add new themes here — no other files need to change.
 */

var THEMES = {

    dark: {
        bg:          '#1e1e1e',
        header:      '#252526',
        text:        '#d4d4d4',
        border:      '#333333',
        lineNum:     '#666666',
        scrollThumb: '#555555',
        borderStyle: 'border: 1px solid #333333;',
        syntax: {
            keyword:  '#569cd6',
            control:  '#c586c0',
            function: '#dcdcaa',
            string:   '#ce9178',
            comment:  '#6a9955',
            number:   '#b5cea8',
            tag:      '#569cd6',
            attr:     '#9cdcfe',
        }
    },

    light: {
        bg:          '#fafafa',
        header:      '#f0f0f0',
        text:        '#333333',
        border:      '#dddddd',
        lineNum:     '#999999',
        scrollThumb: '#cccccc',
        borderStyle: 'border: 1px solid #e5e5e5; box-shadow: 0 4px 15px rgba(0,0,0,0.06);',
        syntax: {
            keyword:  '#0000ff',
            control:  '#af00db',
            function: '#795e26',
            string:   '#a31515',
            comment:  '#008000',
            number:   '#098658',
            tag:      '#800000',
            attr:     '#ff0000',
        }
    },

    dracula: {
        bg:          '#282a36',
        header:      '#21222c',
        text:        '#f8f8f2',
        border:      '#44475a',
        lineNum:     '#6272a4',
        scrollThumb: '#6272a4',
        borderStyle: 'border: 1px solid #44475a;',
        syntax: {
            keyword:  '#ff79c6',
            control:  '#ff79c6',
            function: '#50fa7b',
            string:   '#f1fa8c',
            comment:  '#6272a4',
            number:   '#bd93f9',
            tag:      '#ff79c6',
            attr:     '#50fa7b',
        }
    },

    glass: {
        bg:          'rgba(20, 20, 30, 0.45)',
        header:      'rgba(255, 255, 255, 0.05)',
        text:        '#e2e8f0',
        border:      'rgba(255,255,255,0.12)',
        lineNum:     '#64748b',
        scrollThumb: '#475569',
        borderStyle: 'border: 1px solid rgba(255,255,255,0.15); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); box-shadow: 0 8px 32px rgba(0,0,0,0.3);',
        syntax: {
            keyword:  '#7dd3fc',
            control:  '#c4b5fd',
            function: '#fde68a',
            string:   '#fca5a5',
            comment:  '#94a3b8',
            number:   '#86efac',
            tag:      '#7dd3fc',
            attr:     '#a5f3fc',
        }
    },

};

/**
 * Returns the theme config object for a given name.
 * Falls back to 'dark' if the name is not found.
 * @param {string} name
 * @returns {object}
 */
function getTheme(name) {
    return THEMES[name] || THEMES.dark;
}

/**
 * Generates the CSS rule block for all syntax token span classes,
 * driven entirely by the theme's syntax color map.
 * @param {string} themeName
 * @returns {string}
 */
function buildSyntaxCSS(themeName) {
    var s = getTheme(themeName).syntax;
    return [
        '.keyword  { color: ' + s.keyword  + '; font-weight: 600; }',
        '.control  { color: ' + s.control  + '; }',
        '.function { color: ' + s.function + '; }',
        '.string   { color: ' + s.string   + '; }',
        '.comment  { color: ' + s.comment  + '; font-style: italic; }',
        '.number   { color: ' + s.number   + '; }',
        '.tag      { color: ' + s.tag      + '; }',
        '.attr     { color: ' + s.attr     + '; }',
    ].join('\n');
}


// ─── languageInjector.js ──────────────────────────────────────


/**
 * src/lib/languageInjector.js
 * Language registry for CodUI.
 *
 * Provides registerLanguage() and getLanguage() — the bridge
 * between language rule files (src/lang/*.js) and the highlighter engine.
 *
 * Language files call registerLanguage() as soon as they are loaded.
 * The highlighter calls getLanguage() at tokenization time.
 */

var _langRegistry = {};

/**
 * Registers a language definition under its primary ID and all aliases.
 *
 * @param {string} id          - Primary language identifier e.g. 'javascript'
 * @param {object} definition  - Must have { aliases: string[], tokenize: function }
 */
function registerLanguage(id, definition) {
    if (!id || typeof definition.tokenize !== 'function') {
        return;
    }
    _langRegistry[id.toLowerCase()] = definition;
    var aliases = definition.aliases || [];
    for (var i = 0; i < aliases.length; i++) {
        _langRegistry[aliases[i].toLowerCase()] = definition;
    }
}

/**
 * Retrieves a registered language definition by ID or alias.
 * Returns null if no matching language is found.
 *
 * @param {string} id
 * @returns {object|null}
 */
function getLanguage(id) {
    if (!id) return null;
    return _langRegistry[id.toLowerCase()] || null;
}

/**
 * Returns the list of all registered primary language IDs.
 * Useful for debugging and tooling.
 *
 * @returns {string[]}
 */
function getRegisteredLanguages() {
    var keys = [];
    for (var key in _langRegistry) {
        if (_langRegistry.hasOwnProperty(key)) {
            keys.push(key);
        }
    }
    return keys;
}


// ─── highlighter.js ───────────────────────────────────────────


/**
 * src/lib/highlighter.js
 * Core syntax highlighting engine for CodUI.
 *
 * Delegates all language-specific tokenizing to registered language definitions.
 * Has zero knowledge of any language internals — purely a dispatcher.
 *
 * Depends on: lang-injector.js (getLanguage)
 */

/**
 * Highlights a code string for the given language.
 *
 * Looks up the language in the registry, runs its tokenize() pipeline,
 * and returns an HTML string with <span> tags for each token type.
 *
 * Graceful fallback: if the language is not registered, the raw (escaped)
 * code is returned as-is — no crash, no broken output.
 *
 * @param {string} code - HTML-escaped source code
 * @param {string} lang - Language identifier (e.g. 'js', 'python', 'html')
 * @returns {string}    - HTML string with syntax span tags
 */
function highlight(code, lang) {
    if (!code) return '';

    var definition = getLanguage(lang);

    if (!definition) {
        // Unknown language — return code as plain text (no highlighting)
        return code;
    }

    return definition.tokenize(code);
}


// ─── uiRenderer.js ────────────────────────────────────────────


/**
 * src/lib/uiRenderer.js
 * UI rendering engine for the CodUI Web Component.
 *
 * Generates the complete shadowRoot innerHTML — all CSS styles and markup —
 * driven entirely by theme data from themes.js. Zero hardcoded colors here.
 *
 * Depends on: themes.js (getTheme, buildSyntaxCSS), utils.js (countLines)
 */

/**
 * Builds the HTML for the line number gutter column.
 *
 * @param {number} lineCount - Number of lines in the code block
 * @returns {string} - HTML string of line number divs
 */
function buildLineNumbers(lineCount) {
    var html = '';
    for (var i = 1; i <= lineCount; i++) {
        html += '<div class="line-number">' + i + '</div>';
    }
    return html;
}

/**
 * Renders the complete Web Component shadow DOM.
 * Returns the full innerHTML string including <style> and markup.
 *
 * @param {object} opts
 * @param {string} opts.lang            - Language identifier (display only)
 * @param {string} opts.theme           - Theme name
 * @param {boolean} opts.showLines      - Whether to show the line number gutter
 * @param {string} opts.width           - CSS width value
 * @param {string} opts.height          - CSS max-height value
 * @param {string} opts.highlightedCode - HTML string with <span> tags
 * @param {string} opts.rawCode         - Plain text code (for copy action)
 * @returns {string}
 */
function renderComponent(opts) {
    var lang            = opts.lang || 'text';
    var theme           = opts.theme || 'dark';
    var showLines       = opts.showLines || false;
    var width           = opts.width || '100%';
    var height          = opts.height || 'auto';
    var highlightedCode = opts.highlightedCode || '';

    var t         = getTheme(theme);
    var syntaxCSS = buildSyntaxCSS(theme);

    // ── Code content HTML ─────────────────────────────────────────────────────
    var codeContentHTML = '';
    if (showLines) {
        var lineCount      = countLines(highlightedCode.replace(/<[^>]+>/g, ''));
        var lineNumbersHTML = buildLineNumbers(lineCount);
        codeContentHTML = [
            '<div class="code-grid">',
            '  <div class="line-numbers-col" aria-hidden="true">' + lineNumbersHTML + '</div>',
            '  <pre class="code-col"><code>' + highlightedCode + '</code></pre>',
            '</div>',
        ].join('\n');
    } else {
        codeContentHTML = '<pre class="pre-container"><code>' + highlightedCode + '</code></pre>';
    }

    // ── Styles ────────────────────────────────────────────────────────────────
    var styles = [
        ':host {',
        '    display: block;',
        '    width: 100%;',
        '    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;',
        '    box-sizing: border-box;',
        '}',
        '*, *:before, *:after { box-sizing: inherit; }',

        '.window {',
        '    width: ' + width + ';',
        '    max-height: ' + height + ';',
        '    background: ' + t.bg + ';',
        '    border-radius: 12px;',
        '    overflow: hidden;',
        '    display: flex;',
        '    flex-direction: column;',
        '    ' + t.borderStyle,
        '    transition: background-color 0.3s ease, border-color 0.3s ease;',
        '}',

        '.header {',
        '    background: ' + t.header + ';',
        '    padding: 10px 16px;',
        '    display: flex;',
        '    justify-content: space-between;',
        '    align-items: center;',
        '    border-bottom: 1px solid ' + t.border + ';',
        '    user-select: none;',
        '}',

        '.controls { display: flex; gap: 8px; }',
        '.dot { width: 12px; height: 12px; border-radius: 50%; }',
        '.dot.red    { background: #ff5f56; }',
        '.dot.yellow { background: #ffbd2e; }',
        '.dot.green  { background: #27c93f; }',

        '.actions { display: flex; gap: 12px; align-items: center; }',
        '.lang-badge {',
        '    color: ' + t.lineNum + ';',
        '    font-size: 11px;',
        '    text-transform: uppercase;',
        '    font-weight: 700;',
        '    letter-spacing: 0.6px;',
        '}',

        '.copy-btn {',
        '    background: transparent;',
        '    border: 1px solid ' + t.border + ';',
        '    color: ' + t.text + ';',
        '    padding: 4px 10px;',
        '    border-radius: 6px;',
        '    font-size: 12px;',
        '    cursor: pointer;',
        '    transition: all 0.2s ease-in-out;',
        '    font-family: inherit;',
        '}',
        '.copy-btn:hover { background: rgba(128,128,128,0.12); }',
        '.copy-btn.copied { background: #27c93f; border-color: #27c93f; color: #000; font-weight: 700; }',

        '.content-wrapper { overflow: auto; flex-grow: 1; }',

        '.pre-container {',
        '    margin: 0;',
        '    padding: 20px;',
        '    color: ' + t.text + ';',
        '    font-size: 14px;',
        '    line-height: 1.65;',
        '    white-space: pre;',
        '}',

        '.code-grid { display: flex; min-width: max-content; }',
        '.line-numbers-col {',
        '    padding: 20px 10px 20px 16px;',
        '    text-align: right;',
        '    color: ' + t.lineNum + ';',
        '    background: rgba(0,0,0,0.10);',
        '    border-right: 1px solid ' + t.border + ';',
        '    user-select: none;',
        '    font-size: 14px;',
        '    line-height: 1.65;',
        '    min-width: 42px;',
        '}',
        '.code-col {',
        '    margin: 0;',
        '    padding: 20px;',
        '    color: ' + t.text + ';',
        '    font-size: 14px;',
        '    line-height: 1.65;',
        '    flex-grow: 1;',
        '    white-space: pre;',
        '}',

        '.content-wrapper::-webkit-scrollbar { width: 8px; height: 8px; }',
        '.content-wrapper::-webkit-scrollbar-track { background: transparent; }',
        '.content-wrapper::-webkit-scrollbar-thumb { background: ' + t.scrollThumb + '; border-radius: 4px; }',
        '.content-wrapper::-webkit-scrollbar-thumb:hover { background: ' + t.scrollThumb + '; opacity: 0.8; }',

        syntaxCSS,
    ].join('\n');

    // ── Markup ────────────────────────────────────────────────────────────────
    return [
        '<style>' + styles + '</style>',
        '<div class="window">',
        '  <div class="header">',
        '    <div class="controls">',
        '      <div class="dot red"></div>',
        '      <div class="dot yellow"></div>',
        '      <div class="dot green"></div>',
        '    </div>',
        '    <div class="actions">',
        '      <span class="lang-badge">' + escapeHTML(lang) + '</span>',
        '      <button class="copy-btn" id="codui-copy-btn">Copy</button>',
        '    </div>',
        '  </div>',
        '  <div class="content-wrapper">',
        '    ' + codeContentHTML,
        '  </div>',
        '</div>',
    ].join('\n');
}


// ─── bash.js ──────────────────────────────────────────────────


/**
 * src/lang/bash.js
 * Syntax rules for Bash, Shell scripts.
 *
 * Aliases: sh, shell
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('bash', {
    aliases: ['sh', 'shell'],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. Comments
        code = code.replace(PATTERNS.COMMENT_HASH(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });

        // 2. Strings
        code = code.replace(PATTERNS.STRING_DOUBLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_SINGLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 3. Variable expansions
        code = code.replace(PATTERNS.BASH_VAR(), function (m) {
            return protect('<span class="number">' + m + '</span>');
        });

        // 4. Keywords
        var keywords = [
            'export', 'local', 'readonly', 'source', 'declare',
            'unset', 'echo', 'printf', 'set', 'alias', 'unalias',
            'cd', 'pwd', 'ls', 'mkdir', 'rm', 'cp', 'mv', 'cat',
            'grep', 'sed', 'awk', 'curl', 'chmod', 'chown',
        ];
        code = code.replace(makeKeywordRegex(keywords), function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 5. Control flow
        var control = [
            'if', 'then', 'else', 'elif', 'fi',
            'for', 'while', 'until', 'do', 'done',
            'case', 'esac', 'in', 'function',
            'return', 'exit', 'break', 'continue',
        ];
        code = code.replace(makeKeywordRegex(control), function (m) {
            return protect('<span class="control">' + m + '</span>');
        });

        // 6. Restore
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── css.js ───────────────────────────────────────────────────


/**
 * src/lang/css.js
 * Syntax rules for CSS, SCSS, and Less.
 *
 * Aliases: scss, less
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('css', {
    aliases: ['scss', 'less'],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. Block comments
        code = code.replace(PATTERNS.COMMENT_BLOCK(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });

        // 2. String values
        code = code.replace(PATTERNS.STRING_DOUBLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_SINGLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 3. CSS custom properties / variables: --primary-color
        code = code.replace(PATTERNS.CSS_VAR(), function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 4. Numbers with optional units: 12px, 1.5rem, 100%, 0s
        code = code.replace(PATTERNS.NUMBER_CSS(), function (m) {
            return protect('<span class="number">' + m + '</span>');
        });

        // 5. Property names: word before colon
        code = code.replace(PATTERNS.CSS_PROP(), function (m) {
            return protect('<span class="attr">' + m + '</span>');
        });

        // 6. At-rules: @media, @keyframes, @import, @mixin, etc.
        code = code.replace(/@[\w-]+/g, function (m) {
            return protect('<span class="control">' + m + '</span>');
        });

        // 7. Restore
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── html.js ──────────────────────────────────────────────────


/**
 * src/lang/html.js
 * Syntax rules for HTML and XML.
 *
 * Note: code arrives HTML-escaped — < is &lt;, > is &gt;, & is &amp;
 * All tag/comment patterns must account for this.
 *
 * Aliases: xml
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('html', {
    aliases: ['xml'],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. HTML comments: &lt;!-- ... --&gt;
        code = code.replace(PATTERNS.COMMENT_HTML(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });

        // 2. Attribute string values: "..." and '...'
        code = code.replace(PATTERNS.STRING_DOUBLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_SINGLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 3. Tag names: &lt;div, &lt;/span, etc.
        code = code.replace(PATTERNS.HTML_TAG(), function (_, bracket, tagName) {
            return bracket + protect('<span class="tag">' + tagName + '</span>');
        });

        // 4. Attribute names: word immediately before =
        code = code.replace(PATTERNS.HTML_ATTR(), function (m) {
            return protect('<span class="attr">' + m + '</span>');
        });

        // 5. Restore
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── javascript.js ────────────────────────────────────────────


/**
 * src/lang/javascript.js
 * Syntax rules for JavaScript and TypeScript.
 *
 * Aliases: js, ts, jsx, tsx, typescript
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('javascript', {
    aliases: ['js', 'ts', 'jsx', 'tsx', 'typescript'],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. Comments
        code = code.replace(PATTERNS.COMMENT_BLOCK(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });
        code = code.replace(PATTERNS.COMMENT_SLASH(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });

        // 2. Strings
        code = code.replace(PATTERNS.STRING_BACKTICK(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_DOUBLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_SINGLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 3. Numbers
        code = code.replace(PATTERNS.NUMBER_GENERAL(), function (m) {
            return protect('<span class="number">' + m + '</span>');
        });

        // 4. Keywords
        var keywords = [
            'const', 'let', 'var', 'function', 'class', 'extends', 'super', 'static',
            'new', 'this', 'import', 'export', 'default', 'from', 'as',
            'async', 'await', 'typeof', 'instanceof', 'void', 'delete',
            'interface', 'type', 'enum', 'namespace', 'declare', 'abstract',
            'implements', 'readonly', 'keyof', 'infer', 'in', 'of',
        ];
        code = code.replace(makeKeywordRegex(keywords), function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 5. Control flow
        var control = [
            'return', 'if', 'else', 'for', 'while', 'do', 'switch', 'case',
            'break', 'continue', 'throw', 'try', 'catch', 'finally', 'yield',
        ];
        code = code.replace(makeKeywordRegex(control), function (m) {
            return protect('<span class="control">' + m + '</span>');
        });

        // 6. Function calls
        code = code.replace(PATTERNS.FUNCTION_CALL(), function (m) {
            return protect('<span class="function">' + m + '</span>');
        });

        // 7. Restore all protected tokens
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── json.js ──────────────────────────────────────────────────


/**
 * src/lang/json.js
 * Syntax rules for JSON.
 *
 * Aliases: none
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('json', {
    aliases: [],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. Object keys: "key": — must come before string values
        code = code.replace(PATTERNS.JSON_KEY(), function (_, key) {
            return protect('<span class="attr">"' + key + '"</span>');
        });

        // 2. String values: "value"
        code = code.replace(PATTERNS.JSON_STRING(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 3. Keywords: true, false, null
        code = code.replace(makeKeywordRegex(['true', 'false', 'null']), function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 4. Numbers
        code = code.replace(PATTERNS.NUMBER_JSON(), function (m) {
            return protect('<span class="number">' + m + '</span>');
        });

        // 5. Restore
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── python.js ────────────────────────────────────────────────


/**
 * src/lang/python.js
 * Syntax rules for Python.
 *
 * Aliases: py
 * Depends on: PATTERNS, makeKeywordRegex (regex.js), registerLanguage (languageInjector.js)
 */

registerLanguage('python', {
    aliases: ['py'],

    tokenize: function (code) {
        var store = [];

        function protect(html) {
            var id = '\x00T' + store.length + 'T\x00';
            store.push(html);
            return id;
        }

        // 1. Triple-quoted strings
        code = code.replace(/"""([\s\S]*?)"""/g, function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(/'''([\s\S]*?)'''/g, function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 2. Hash comments
        code = code.replace(PATTERNS.COMMENT_HASH(), function (m) {
            return protect('<span class="comment">' + m + '</span>');
        });

        // 3. Single-line strings
        code = code.replace(PATTERNS.STRING_DOUBLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });
        code = code.replace(PATTERNS.STRING_SINGLE(), function (m) {
            return protect('<span class="string">' + m + '</span>');
        });

        // 4. Numbers
        code = code.replace(PATTERNS.NUMBER_GENERAL(), function (m) {
            return protect('<span class="number">' + m + '</span>');
        });

        // 5. Keywords
        var keywords = [
            'def', 'class', 'import', 'from', 'as', 'with',
            'lambda', 'yield', 'pass', 'raise', 'global', 'nonlocal',
            'del', 'assert', 'True', 'False', 'None', 'self', 'cls',
        ];
        code = code.replace(makeKeywordRegex(keywords), function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 6. Control flow
        var control = [
            'return', 'if', 'elif', 'else', 'for', 'while',
            'try', 'except', 'finally', 'in', 'not', 'and',
            'or', 'is', 'break', 'continue', 'async', 'await',
        ];
        code = code.replace(makeKeywordRegex(control), function (m) {
            return protect('<span class="control">' + m + '</span>');
        });

        // 7. Decorators (@decorator)
        code = code.replace(/@([\w.]+)/g, function (m) {
            return protect('<span class="keyword">' + m + '</span>');
        });

        // 8. Function calls
        code = code.replace(PATTERNS.FUNCTION_CALL(), function (m) {
            return protect('<span class="function">' + m + '</span>');
        });

        // 9. Restore
        return code.replace(/\x00T(\d+)T\x00/g, function (_, i) {
            return store[+i];
        });
    }
});


// ─── codui.core.js ────────────────────────────────────────────


/**
 * src/codui.core.js
 * CodUI Web Component definition.
 *
 * This is the entry point class. It coordinates attributes, handles
 * component lifecycle, and triggers rendering and copy logic.
 *
 * Depends on:
 *   - utils.js (stripNewlines, escapeHTML)
 *   - highlighter.js (highlight)
 *   - uiRenderer.js (renderComponent)
 */

class CodUI extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
    }

    connectedCallback() {
        this.render();
    }

    static get observedAttributes() {
        return ['theme', 'lang', 'line-numbers', 'width', 'height'];
    }

    attributeChangedCallback() {
        this.render();
    }

    /**
     * Public API: Programmatically highlight code string.
     */
    highlight(code, lang) {
        return highlight(code, lang);
    }

    static highlight(code, lang) {
        return highlight(code, lang);
    }

    render() {
        var width     = this.getAttribute('width') || '100%';
        var height    = this.getAttribute('height') || 'auto';
        var lang      = this.getAttribute('lang') || 'js';
        var theme     = this.getAttribute('theme') || 'dark';
        var showLines = this.getAttribute('line-numbers') === 'true';

        // 1. Get raw content from component body
        var rawCode = this.innerHTML;
        if (!rawCode || !rawCode.trim()) {
            rawCode = this.textContent || '';
        }
        
        // Clean leading/trailing empty lines
        rawCode = stripNewlines(rawCode);

        // 2. Prep code for copy functionality and rendering
        var cleanCodeForCopy = rawCode;
        var escapedCode      = escapeHTML(rawCode);

        // 3. Apply syntax highlighting
        var highlightedCode = highlight(escapedCode, lang);

        // 4. Render HTML/CSS markup into Shadow DOM
        this.shadowRoot.innerHTML = renderComponent({
            lang: lang,
            theme: theme,
            showLines: showLines,
            width: width,
            height: height,
            highlightedCode: highlightedCode,
            rawCode: cleanCodeForCopy
        });

        // 5. Wire up the copy button event listener
        var copyBtn = this.shadowRoot.getElementById('codui-copy-btn');
        if (copyBtn) {
            copyBtn.addEventListener('click', function () {
                // Modern Clipboard API with simple textarea fallback
                if (navigator.clipboard && navigator.clipboard.writeText) {
                    navigator.clipboard.writeText(cleanCodeForCopy)
                        .then(showCopiedState)
                        .catch(function (err) {
                            console.error("Clipboard API copy failed, using fallback: ", err);
                            fallbackCopy(cleanCodeForCopy);
                        });
                } else {
                    fallbackCopy(cleanCodeForCopy);
                }
            });
        }

        function showCopiedState() {
            if (!copyBtn) return;
            copyBtn.textContent = 'Copied!';
            copyBtn.classList.add('copied');
            setTimeout(function () {
                copyBtn.textContent = 'Copy';
                copyBtn.classList.remove('copied');
            }, 2000);
        }

        function fallbackCopy(text) {
            var textarea = document.createElement('textarea');
            textarea.value = text;
            // Prevent scrolling on focus
            textarea.style.top = '0';
            textarea.style.left = '0';
            textarea.style.position = 'fixed';
            document.body.appendChild(textarea);
            textarea.focus();
            textarea.select();
            try {
                document.execCommand('copy');
                showCopiedState();
            } catch (err) {
                console.error("Fallback copy failed: ", err);
            }
            document.body.removeChild(textarea);
        }
    }
}

customElements.define('cod-ui', CodUI);

})();
