/**
 * scripts/build.js
 * CodUI v2.0.8 — Zero-dependency build script.
 *
 * Concatenates all src/ modules in dependency order,
 * wraps the bundle in an IIFE, and writes to codUI.js at root.
 *
 * Usage: node scripts/build.js
 */

const fs   = require('fs');
const path = require('path');

// ── ANSI colors for terminal output ──────────────────────────────────────────
const c = {
    reset:  '\x1b[0m',
    bold:   '\x1b[1m',
    green:  '\x1b[32m',
    yellow: '\x1b[33m',
    cyan:   '\x1b[36m',
    red:    '\x1b[31m',
    gray:   '\x1b[90m',
    dim:    '\x1b[2m',
};

// ── Build order (CRITICAL — do not reorder) ───────────────────────────────────
const ORDERED_FILES = [
    'src/lib/utils.js',
    'src/lib/regex.js',
    'src/lib/themes.js',
    'src/lib/lang-injector.js',
    'src/lib/highlighter.js',
    'src/lib/ui-render.js',
];

const LANG_DIR      = 'src/lang';
const CORE_FILE     = 'src/codui.core.js';
const OUTPUT_FILE   = 'codUI.js';

// ── Version banner (injected at top of codUI.js) ──────────────────────────────
const BANNER = `/**
 * codUI.js — v2.0.8
 * Lightweight, zero-dependency Web Component for code syntax highlighting.
 *
 * !! DO NOT EDIT THIS FILE DIRECTLY !!
 * This file is auto-generated by: node scripts/build.js
 * Source files live in: src/
 *
 * Usage: <cod-ui lang="js" theme="dark" line-numbers="true">...</cod-ui>
 * Docs:  https://github.com/praTeek271/codUI
 */\n\n`;

// ── Helpers ───────────────────────────────────────────────────────────────────
function readFile(filePath) {
    const abs = path.resolve(__dirname, '..', filePath);
    if (!fs.existsSync(abs)) {
        console.error(`${c.red}✖ Missing file: ${filePath}${c.reset}`);
        process.exit(1);
    }
    return fs.readFileSync(abs, 'utf8').trim();
}

function separator(label) {
    return `\n// ${'─'.repeat(3)} ${label} ${'─'.repeat(Math.max(0, 57 - label.length))}\n`;
}

// ── Build ─────────────────────────────────────────────────────────────────────
console.log(`\n${c.cyan}${c.bold}╔══════════════════════════════════════════════════╗`);
console.log(`║        CodUI v2.0.8  —  Build Script            ║`);
console.log(`╚══════════════════════════════════════════════════╝${c.reset}\n`);

const startTime = Date.now();
const chunks    = [];

// 1. Core lib modules (ordered)
for (const filePath of ORDERED_FILES) {
    process.stdout.write(`${c.gray}  bundling ${filePath}...${c.reset} `);
    chunks.push(separator(path.basename(filePath)));
    chunks.push(readFile(filePath));
    console.log(`${c.green}✔${c.reset}`);
}

// 2. Language rule files (auto-discovered, sorted)
const langDir = path.resolve(__dirname, '..', LANG_DIR);
if (!fs.existsSync(langDir)) {
    console.error(`${c.red}✖ Language directory not found: ${LANG_DIR}${c.reset}`);
    process.exit(1);
}
const langFiles = fs.readdirSync(langDir)
    .filter(f => f.endsWith('.js'))
    .sort()
    .map(f => `${LANG_DIR}/${f}`);

for (const filePath of langFiles) {
    process.stdout.write(`${c.gray}  bundling ${filePath}...${c.reset} `);
    chunks.push(separator(path.basename(filePath)));
    chunks.push(readFile(filePath));
    console.log(`${c.green}✔${c.reset}`);
}

// 3. Web component core (always last)
process.stdout.write(`${c.gray}  bundling ${CORE_FILE}...${c.reset} `);
chunks.push(separator(path.basename(CORE_FILE)));
chunks.push(readFile(CORE_FILE));
console.log(`${c.green}✔${c.reset}`);

// 4. Assemble final bundle (IIFE wrapped)
const bundle = BANNER
    + `(function () {\n'use strict';\n\n`
    + chunks.join('\n\n')
    + `\n\n})();\n`;

// 5. Write output
const outPath = path.resolve(__dirname, '..', OUTPUT_FILE);
fs.writeFileSync(outPath, bundle, 'utf8');

const duration = Date.now() - startTime;
const sizeKB   = (bundle.length / 1024).toFixed(2);

console.log(`\n${c.gray}──────────────────────────────────────────────────────${c.reset}`);
console.log(`${c.bold}  Output:   ${c.reset}${c.yellow}${OUTPUT_FILE}${c.reset}`);
console.log(`${c.bold}  Size:     ${c.reset}${c.yellow}${sizeKB} KB${c.reset} ${c.dim}(unminified)${c.reset}`);
console.log(`${c.bold}  Duration: ${c.reset}${c.yellow}${duration}ms${c.reset}`);
console.log(`\n${c.green}${c.bold}  ✅  Build complete!${c.reset}\n`);
